### ISSUE TITLE
Working with local modules in Thonny

### ISSUE THREAD

**Issue by lowfatcode** [raspberrypi/thonny-pico#12]
I'm currently working on some Python modules to support various bits of hardware - I'm using Thonny since it provides an efficient edit, upload, and run cycle with a convenient output shell. This will be really nice for beginners!

However I can't seem to find a way to have it easily upload both my module code and the test script that imports it. The only way that seems possible is to explicitly save the module file to the device using "Save copy..." which requires multiple clicks and leaves the code on the device (so there is no local copy updated for source control without taking extra steps).

I suspect this is just out of scope of Thonny currently but it seems like a common usecase for projects as they get more complicated. I don't know if this is a liimitation imposed due to other hardware supported by Thonny but I figured since @aivarannamaa is here it was worth asking. :-)

I guess I'll probably shift my process over to using VSCode and `rshell` in the short term but I think this is a feature that end users would also find invaluable and/or a limitation that they may find confusing.

For what it's worth my initial "instinct" was that every currently open file would automatically be uploaded to the device before running - that would seem like a logical way to approach it though I'm sure it's not that simple. :-)

**Comment by aivarannamaa** [comment]
Moved to https://github.com/thonny/thonny/issues/1192
