### ISSUE TITLE
Lack of RTC Support Brings Up Warnings

### ISSUE THREAD

**Issue by ghalfacree** [raspberrypi/thonny-pico#4]
Not sure if this is the right place to report it, but Thonny 3.3.0 brings up warnings on connection to Pico owing to the MicroPython port's lack of RTC support.

![Screenshot from 2020-11-03 16-08-10](https://user-images.githubusercontent.com/1130041/98013602-79577d00-1df2-11eb-8213-0d0896e3bd53.png)

(The screenshot shows "MicroPython (generic)" as the backend, but I've confirmed the problem with both generic and Pico backends.)

There's an open issue about RTC support on the MicroPython port repo, but I don't know if support will be ready by launch; @aivarannamaa, would removing the attempted RTC synchronisation work as a temporary fix - then adding it back in when RTC support has been confirmed?

**Comment by aivarannamaa** [comment]
Moved to https://github.com/thonny/thonny/issues/1563
